globalFolder: "D:\\AppData\\Yarn\\Berry"
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  bootstrap@*:
    dependencies:
      jquery: "*"
      popper.js: "*"
  firebase-admin@*:
    dependencies:
      "@firebase/app-compat": "*"
  next-pwa@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"
