globalFolder: "D:\\AppData\\Yarn\\Berry"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
packageExtensions:
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
  "firebase-admin@*":
    dependencies:
      "@firebase/app-compat": "*"
  "next-pwa@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "*"
  "bootstrap@*":
    dependencies:
      "jquery": "*"
      "popper.js": "*"
