backend:
  name: github
  repo: sandipv22/afterroot
media_folder: static/assets
public_folder: /assets
collections:
  - name: posts
    label: Post
    folder: posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
